### ISSUE TITLE
Crash when loading an XCF with Additive layer

### ISSUE THREAD

**Issue by ali1234** [FHPythonUtils/LayeredImage#3]
File: [test.xcf.gz](https://github.com/FHPythonUtils/LayeredImage/files/6613052/test.xcf.gz)

Code:
```
from layeredimage.io import openLayerImage

xcf = openLayerImage('test.xcf')
xcf.getFlattenLayers().show()
```

Result:

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    xcf.getFlattenLayers().show()
  File "/home/al/Source/32blit/32blit-tools/venv/lib/python3.8/site-packages/layeredimage/layeredimage.py", line 96, in getFlattenLayers
    return flattenAll(self.layersAndGroups, self.dimensions, ignoreHidden)
  File "/home/al/Source/32blit/32blit-tools/venv/lib/python3.8/site-packages/layeredimage/layeredimage.py", line 261, in flattenAll
    flattenedSoFar = flattenLayerOrGroup(
  File "/home/al/Source/32blit/32blit-tools/venv/lib/python3.8/site-packages/layeredimage/layeredimage.py", line 237, in flattenLayerOrGroup
    return blendLayers(
  File "/home/al/Source/32blit/32blit-tools/venv/lib/python3.8/site-packages/layeredimage/blend.py", line 122, in blendLayers
    return bLayers(background, foreground, blendTypeMap[blendType], opacity)
KeyError: <BlendType.ADDITIVE: 3>
```

Note: This happens because Additive is missing from the blendTypeMap in blend.py. It is defined in the BlendType enum and can be added to the mapping, and doing so will allow the program to run and display an image. However, it is rendered incorrectly (the red blob should not be visible according to GIMP.)

**Comment by ali1234** [comment]
Also one other defined layer type from the enum is missing from the map: Glow. This doesn't seem to be an XCF layer type.

**Comment by FredHappyface** [comment]
So I've made a start on this...

I've made better use leveraging blendmodes functions directly reducing code duplication and hopefully making it easier to find issues in upstream libs (turns out I missed loads from the mapping :o)

As far as the remaining issue goes - I'm going to need to refresh my memory on how it all fits together

**Comment by FredHappyface** [comment]
Having looked at Gimp and paint.net it looks like they have different opinions on how to render additive (PDN) vs addition (gimp). 

Basically it seems that Gimp does something like source atop whereas PDN seems to use source over (personally makes more sense to me) 

Or might be dest atop and dest over...

This site might help if I have made no sense: https://docs.geoserver.org/stable/en/user/styling/sld/extensions/composite-blend/modes.html

**Comment by ali1234** [comment]
I'm not sure about the terminology but it seems to me like Additive layers in GIMP aren't added to the alpha channel, only RGB. This might apply to other layer types too.

**Comment by FredHappyface** [comment]
Seems like it 

I'm going to take a look at how pyora does blending to see if this differs - it seems that gimp treats ora additive in the same way as it does xcf but I don't know if that is intentional. (I mention this as the blending I use was adapted from that project amongst others)

**Comment by FredHappyface** [comment]
Interestingly (perhaps) is that ora svg:plus composition behaves in a similar way to how the Additive function works in blendtypes (docs: https://www.w3.org/TR/compositing-1/#porterduffcompositingoperators_plus + further reading: https://keithp.com/~keithp/porterduff/p253-porter.pdf). Krita behaves this way too. Whereas Gimp treats it in the same way as it does additive. 

Export xcf to psd with Gimp 
Gimp: Addition - Can see red mark, composite mode is set to union 
Krita: Linear Dodge - Can see red mark

Export xcf to ora with Gimp (data loss - ie. fails to preserve blend type)
Gimp: Normal - Can see red mark
Krita: Normal - Can see red mark

Convert xcf to ora with layeredimage (converted to svg:plus)
Gimp: Addition (legacy) - Cannot see red mark
Krita: Addition - Can see red mark

**Comment by FredHappyface** [comment]
Just to clarify these results, it seems that Gimp is the anomaly here in terms of how it interprets "additive"
