### ISSUE TITLE
Bug: dimensions auto-calculation disregards layer offsets

### ISSUE THREAD

**Issue by denilsonsa** [FHPythonUtils/LayeredImage#7]
## Before You Begin

Before proceeding, please make sure to follow these steps:

- [x] I have checked for similar issues in the project's issue tracker.
- [x] I have searched closed issues to see if a similar problem was reported
  before.

### Description

When creating a new `LayeredImage` from a list of layers, the code auto-calculates the total dimension of the image. However, it ignores the layer offset information.

* https://github.com/FHPythonUtils/LayeredImage/blob/69c9eae2ab9ce4ef609baac60cfbc35d5eea381d/layeredimage/layeredimage.py#L38-L43
* https://github.com/FHPythonUtils/LayeredImage/blob/69c9eae2ab9ce4ef609baac60cfbc35d5eea381d/layeredimage/layergroup.py#L168-L173

Here's a snippet of my code:

```python
    img = LayeredImage([
        Layer(
            name=("foobar-%06d" % n),
            image=load_image(n),
            offsets=offsets,
        )
        for (n, offsets) in calculated_offsets
    ])
```

I have a bunch of small images, and they all have a small offset in relation to each other, essentially stichting them together for a large image.

### Expected Behavior

The `LayeredImage.dimensions` would consider the offsets, so that exporting the image would work correctly.

### Actual Behavior

The image dimensions are the dimensions of the largest layer, disregarding the layer position.

### Workaround

```python
    img.dimensions = (
        max(layer.dimensions[0] + layer.offsets[0] for layer in img.layers),
        max(layer.dimensions[1] + layer.offsets[1] for layer in img.layers),
    )
```

## System Information

- Operating System (OS): Manjaro Linux
- Python 3.11.5
- layeredimage version 2023, installed using `pip` into a virtualenv

**Comment by FredHappyface** [comment]
Hi thanks for opening this! 

I'll have a look hopefully this week. If you've got some code that breaks it could you drop a copy so I can write some tests?

Cheers :)

**Comment by denilsonsa** [comment]
The code was some earlier iteration on one of these notebooks: https://gist.github.com/denilsonsa/2922060be4fcddcf7a4e3745a78b5752/revisions (sidenote: I ended up moving from `layeredimage` to `pyora` because rendering the thumbnail was taking too long, and with pyora I could pass a pre-rendered thumbnail image.)

Sorry I don't have a minimal testcase, but should be "easy enough" to reproduce by having two layers with a noticeable offset.

**Comment by FredHappyface** [comment]
No worries! Thank you for getting back to me on this. And yeah layeredimage is very much meant to be a convienience lib that wraps other existing libs specific to each format 

That being said, the ability of passing a pre-rendered thumbnail definitely seems useful! I'm really curious on how bad the perf hit was? I wouldn't have assumed it would be too bad as we use blendmodes which in turn uses numpy which is pretty optimised

**Comment by denilsonsa** [comment]
> I'm really curious on how bad the perf hit was?

Without generating the thumbnail, the `.ora` file was written in a few seconds. With generating the thumbnail, it was taking many minutes of high CPU and high RAM usage. So many minutes that I usually interrupted it.

> I wouldn't have assumed it would be too bad as we use blendmodes which in turn uses numpy which is pretty optimised

As optimized as it can be, it was still reading/writing a huge amount of data. The images in question were made of hundreds of screenshots stitched together. Imagine 100, 200, maybe 400 screenshots. Each one with a small offset over the previous one. GIMP itself can handle those images just fine (after taking a long time importing from the `.ora` file, but that's because the importer is slow). So, I'm guessing their thumbnail-generation logic isn't well optimized for my case.

**Comment by FredHappyface** [comment]
fixed in https://github.com/FHPythonUtils/LayeredImage/releases/tag/2024.3
