### ISSUE TITLE
smart object

### ISSUE THREAD

**Issue by milqnomadu** [FHPythonUtils/LayeredImage#8]
(1) I was trying to replace the image inside a smart object, save it and then export the psd as an image. I'm aware from the table this might not be possible.

(2) Retrieve the information from the smart object and have it replicated in PIL: opacity, position, bbox, perspective and warp. However using psd-tools Warp I'm not able to retrieve.

Is it possible to either (1) or (2) with this repo?

Sorry if I disturbed you in any way, hope you have a great day!

**Comment by FredHappyface** [comment]
Hi thanks for this

My knowledge of smart objects is pretty poor so please forgive me if I'm talking nonesense on this. I've assumed that these are something in photoshop 

1) Unfortunately it is not possible to write to psd with this lib or with `psd-tools` last I checked 

2) as this repo wraps psd-tools we only support what they do. It may be worth either tryign to open the psd in a tool like photoshop/ gimp and exporting to a more generic format like .ora (https://www.openraster.org/baseline/baseline.html)

For context, layeredimage has 3 main purposes, 
- to read and write to ora - an internal format can be used but tbh I strongly discourage this (see also https://xkcd.com/927/). 
- to do stuff with layered images programmatically 
- as a simple tool to pull data from proprietry image files - though for this photoshop/ gimp may do a significantly better job of supporting these

**Comment by milqnomadu** [comment]
Hi,

Don’t know what ora is. What I need is to just be able to switch inside
smart object various images I give so that I can programmatically insert
images inside the SO and they have applied the perspective, distort, warp,
opacity properties of the SO and I can then export the full image.

Would this be possible?

Il giorno lun 26 ago 2024 alle 16:16 Kieran W ***@***.***> ha
scritto:

**Comment by FredHappyface** [comment]
> My knowledge of smart objects is pretty poor so please forgive me if I'm talking nonesense on this. I've assumed that these are something in photoshop

I don't know tbh, sorry
